package com.nexradnow.android.model;

/**
 * Generated by the location selection activity and caught (hopefully) by the application
 * Created by hobsonm on 10/14/15.
 */
public class LocationSelectionEvent {
    public enum SelectionType {GPS, NEXRADSTATION, CITYSTATE};

    protected SelectionType type;
    protected String cityState;
    protected NexradStation station;

    public LocationSelectionEvent(SelectionType type) {
        this.type = type;
    }

    public String getCityState() {
        return cityState;
    }

    public void setCityState(String cityState) {
        this.cityState = cityState;
    }

    public NexradStation getStation() {
        return station;
    }

    public void setStation(NexradStation station) {
        this.station = station;
    }

    public SelectionType getType() {
        return type;
    }
}
